# Generated by Django 4.0.2 on 2022-02-17 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Note_topic', models.CharField(max_length=20, verbose_name='Тема заметки')),
                ('description', models.TextField(blank=True, default='Без темы', max_length=256, verbose_name='Описание темы')),
                ('slug', models.SlugField(max_length=256, unique=True)),
            ],
            options={
                'verbose_name': 'Тема заметки',
                'verbose_name_plural': 'Темы заметок',
                'ordering': ('Note_topic',),
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=256, unique=True)),
                ('title', models.CharField(max_length=20, verbose_name='Название заметки')),
                ('note_field', models.TextField(verbose_name='Содержание заметки')),
                ('pub_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('Note_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note_board.topic', verbose_name='Тема заметки')),
            ],
            options={
                'verbose_name': 'Название заметки',
                'verbose_name_plural': 'Названия заметок',
                'ordering': ('pub_date',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
